# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 21, 6, 47, 20, 153030, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
