# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
