# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20170726_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('view', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(related_name='asked', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
