# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
