# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170726_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
