# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Channel'),
            preserve_default=False,
        ),
    ]
