# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_question_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='member',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='color',
            field=models.CharField(max_length=10, verbose_name='색'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=255, verbose_name='그룹 소개'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='그룹 이름'),
        ),
        migrations.AlterField(
            model_name='question',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='blog.Channel'),
        ),
    ]
